### ISSUE TITLE
hello,bro, where download the  compatible and full client of roseau?

### ISSUE THREAD

**Issue by odasm** [TheAmazingAussie/Roseau#1]
i am newbee, thanks ......please help me?    where dowload the 2001 full client?

**Comment by markhughes** [comment]
it's in the client folder

**Comment by emansom** [comment]
Pssssh, don't let Sulake know!

**Comment by Quackster** [comment]
As @MarkehMe said, you can find all the client files that are compatible in the /client/ folder. It's in a zip file called dcr0910.zip.

Good luck, have fun!
